name: Deploy to ECR

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release"
        required: true
        default: "v0.0.1"

permissions:
  id-token: write
  contents: read

env:
  REGISTRY_ID: 503561419437
  ECR_REGISTRY: 503561419437.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: sas-dev-ecr-repository
  AWS_REGION: us-east-1
  ROLE_ARN: arn:aws:iam::503561419437:role/ecr-deploy-github-action
  IMAGE_NAME: sas-frontend

jobs:
  deploy-ecr-dev:
    if: ${{ github.ref_name == 'main' }}
    concurrency: deploy-ecr-dev
    runs-on: ubuntu-latest
    environment:
      name: dev
    env:
      ENVIRONMENT: dev
      ECS_CLUSTER: "sas-dev"
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials dev account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: sas-github-frontend-deployment
          aws-region: ${{ env.AWS_REGION }}

      - name: Build, tag, and push image to Amazon ECR
        working-directory: ./
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

          # Build the Docker image with the IMAGE_NAME only
          docker build -t ${{ env.IMAGE_NAME }} -f Dockerfile .

          # Tag the image with the full registry and repository
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_NAME }}-latest

          # Delete the latest image tag if it exists before pushing
          aws ecr batch-delete-image --repository-name ${{ env.ECR_REPOSITORY }} --image-ids imageTag=${{ env.IMAGE_NAME }}-latest || true

          # Push the latest tag
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_NAME }}-latest

      - name: Update ECS task definition
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service frontend-task --force-new-deployment

  validate-release:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    needs: deploy-ecr-dev
    environment:
      name: prod
    env:
      ENVIRONMENT: prod
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: github-actions-release
          aws-region: ${{ env.AWS_REGION }}

      - name: Create a Git tag
        run: |
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}

      - name: Build, tag, and push image to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

          # Build the Docker image with the IMAGE_NAME only
          docker build -t ${{ env.IMAGE_NAME }} -f Dockerfile .

          # Tag the image with the full registry and repository using the input tag
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_NAME }}-${{ github.event.inputs.tag }}

          # Push the tagged image
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_NAME }}-${{ github.event.inputs.tag }}
